apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
stringData:
  username: admin
  password: supersecretpassword
  ---
apiVersion: v1
kind: Secret
metadata:
  name: gestionepratiche-ops-secret 
  namespace: n2-api-be
type: Opaque
stringData:
  RegistryAPIConfiguration_CommunicationProxyConnectionStrings_CRP: "Data Source=Data Source=CRPD-NCD-HL61.cpsvcpar.intra,1433;Initial Catalog=BizTier_Services_Catalog;User ID=CP_NBN_USER;Password='Nbn@2016!';"
